#!/usr/bin/env bash
#
# restore.sh
# Validates and restores a backup generated by backup.sh. It never restores
# silently: existing targets are listed and the user must type RESTORE.
#
# Usage:
#   ./scripts/restore.sh backups/full/backup-YYYYMMDD-HHMMSS.tar.gz
#   ./scripts/restore.sh --dry-run /opt/docker/backups/full/backup-....tar.gz

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"
trap 'on_error "$?" "$LINENO"' ERR

RESTORE_TEMP_DIR=""
DRY_RUN=false
BACKUP_FILE=""

usage() {
  cat <<'EOF'
Usage:
  restore.sh [options] BACKUP_FILE

Options:
  --dry-run    Validate and preview restore without copying files
  -n           Alias for --dry-run
  -h, --help   Show this help
EOF
}

parse_args() {
  while [[ "$#" -gt 0 ]]; do
    case "$1" in
      --dry-run|-n)
        DRY_RUN=true
        shift
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      --)
        shift
        ;;
      -*)
        die "Unknown option: $1"
        ;;
      *)
        if [[ -n "${BACKUP_FILE}" ]]; then
          die "Only one backup file can be provided."
        fi
        BACKUP_FILE="$1"
        shift
        ;;
    esac
  done

  if [[ -z "${BACKUP_FILE}" ]]; then
    usage
    exit 1
  fi
}

tar_contains() {
  local backup_file="$1"
  local path="$2"

  tar -tzf "${backup_file}" |
    awk -v path="${path}" '$0 == path || index($0, path "/") == 1 {found = 1} END {exit !found}'
}

sudo_cmd() {
  if [[ "${EUID}" -eq 0 ]]; then
    "$@"
  else
    sudo "$@"
  fi
}

validate_checksum() {
  local backup_file="$1"
  local checksum_file="${backup_file}.sha256"

  [[ -f "${checksum_file}" ]] ||
    die "Checksum file not found: ${checksum_file}"

  sha256sum -c "${checksum_file}" >/dev/null
  ok "SHA-256 checksum valid"
}

# Archive stores DATA_ROOT without leading slash (e.g. opt/docker/...).
archive_data_prefix() {
  local data_root="$1"
  printf '%s\n' "${data_root#/}"
}

main() {
  local temp_dir
  local answer
  local data_root
  local data_prefix
  local archive_data_src=""
  local project_dir
  local project_dirs=(
    compose
    configs
    bootstrap
    scripts
    docs
  )

  parse_args "$@"

  [[ -f "${BACKUP_FILE}" ]] ||
    die "Backup file not found: ${BACKUP_FILE}"

  require_command tar
  require_command sha256sum
  data_root="$(persistent_data_root)"
  data_prefix="$(archive_data_prefix "${data_root}")"

  info "Validating checksum"
  validate_checksum "${BACKUP_FILE}"

  info "Validating archive"
  tar -tzf "${BACKUP_FILE}" >/dev/null
  ok "Archive is readable"

  section "Archive contents"
  tar -tzf "${BACKUP_FILE}" | head -n 80 || true
  info "(listing truncated to 80 lines)"

  for project_dir in compose bootstrap scripts docs; do
    tar_contains "${BACKUP_FILE}" "${project_dir}" ||
      die "Invalid backup: missing ${project_dir}/"
  done

  temp_dir="$(mktemp -d)"
  RESTORE_TEMP_DIR="${temp_dir}"
  trap 'rm -rf "${RESTORE_TEMP_DIR}"' EXIT
  tar -xzf "${BACKUP_FILE}" -C "${temp_dir}"

  section "Restore targets"
  for project_dir in "${project_dirs[@]}"; do
    if [[ -e "${temp_dir}/${project_dir}" ]]; then
      if [[ -e "${PROJECT_ROOT}/${project_dir}" ]]; then
        warn "Existing path will be overwritten after confirmation: ${PROJECT_ROOT}/${project_dir}"
      else
        info "Will create ${PROJECT_ROOT}/${project_dir}"
      fi
    fi
  done

  if [[ -e "${temp_dir}/${data_prefix}" ]]; then
    archive_data_src="${temp_dir}/${data_prefix}"
  elif [[ -e "${temp_dir}/opt/docker" ]]; then
    # Legacy archives always used opt/docker regardless of DATA_ROOT override
    archive_data_src="${temp_dir}/opt/docker"
    warn "Archive uses legacy path opt/docker; will restore into DATA_ROOT=${data_root}"
  fi

  if [[ -n "${archive_data_src}" ]]; then
    if [[ -e "${data_root}" ]]; then
      warn "Existing persistent data will be overwritten after confirmation: ${data_root}"
    else
      info "Will create ${data_root}"
    fi
  else
    warn "Archive does not contain persistent data tree (${data_prefix})"
  fi

  if [[ "${DRY_RUN}" == "true" ]]; then
    ok "Dry run completed. No changes applied."
    return 0
  fi

  printf '\nType RESTORE to continue: '
  if ! read -r answer; then
    die "Restore cancelled."
  fi

  if [[ "${answer}" != "RESTORE" ]]; then
    die "Restore cancelled."
  fi

  section "Restoring project directories"
  for project_dir in "${project_dirs[@]}"; do
    if [[ -e "${temp_dir}/${project_dir}" ]]; then
      rm -rf "${PROJECT_ROOT:?}/${project_dir}"
      cp -a "${temp_dir}/${project_dir}" "${PROJECT_ROOT}/${project_dir}"
      ok "Restored ${project_dir}"
    fi
  done

  if [[ -n "${archive_data_src}" ]]; then
    section "Restoring persistent data to ${data_root}"
    sudo_cmd mkdir -p "$(dirname "${data_root}")"
    sudo_cmd rm -rf "${data_root}"
    sudo_cmd cp -a "${archive_data_src}" "${data_root}"
    ok "Restored ${data_root}"
  fi

  ok "Restore completed."
  info "Next: bash scripts/storage-prepare-dirs.sh && make health"
}

main "$@"
