#!/usr/bin/env bash
#
# restore.sh
# Validates and restores a backup generated by backup.sh. It never restores
# silently: existing targets are listed and the user must type RESTORE.
#
# Usage:
#   ./scripts/restore.sh backups/backup-YYYYMMDD-HHMMSS.tar.gz

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"
trap 'on_error "$?" "$LINENO"' ERR

RESTORE_TEMP_DIR=""

usage() {
  cat <<'EOF'
Usage: restore.sh <backup-file.tar.gz>
EOF
}

tar_contains() {
  local backup_file="$1"
  local path="$2"

  tar -tzf "${backup_file}" |
    awk -v path="${path}" '$0 == path || index($0, path "/") == 1 {found = 1} END {exit !found}'
}

sudo_cmd() {
  if [[ "${EUID}" -eq 0 ]]; then
    "$@"
  else
    sudo "$@"
  fi
}

main() {
  local backup_file="${1:-}"
  local temp_dir
  local answer
  local data_root
  local project_dir
  local project_dirs=(
    compose
    configs
    bootstrap
    scripts
    docs
  )

  [[ -n "${backup_file}" ]] || {
    usage
    exit 1
  }

  [[ -f "${backup_file}" ]] ||
    die "Backup file not found: ${backup_file}"

  require_command tar
  data_root="$(persistent_data_root)"

  info "Validating archive"
  tar -tzf "${backup_file}" >/dev/null

  for project_dir in compose bootstrap scripts docs; do
    tar_contains "${backup_file}" "${project_dir}" ||
      die "Invalid backup: missing ${project_dir}/"
  done

  temp_dir="$(mktemp -d)"
  RESTORE_TEMP_DIR="${temp_dir}"
  trap 'rm -rf "${RESTORE_TEMP_DIR}"' EXIT
  tar -xzf "${backup_file}" -C "${temp_dir}"

  section "Restore targets"
  for project_dir in "${project_dirs[@]}"; do
    if [[ -e "${temp_dir}/${project_dir}" ]]; then
      if [[ -e "${PROJECT_ROOT}/${project_dir}" ]]; then
        warn "Existing path will be overwritten after confirmation: ${PROJECT_ROOT}/${project_dir}"
      else
        info "Will create ${PROJECT_ROOT}/${project_dir}"
      fi
    fi
  done

  if [[ -e "${temp_dir}/opt/docker" ]]; then
    if [[ -e "${data_root}" ]]; then
      warn "Existing persistent data will be overwritten after confirmation: ${data_root}"
    else
      info "Will create ${data_root}"
    fi
  else
    warn "Archive does not contain opt/docker"
  fi

  printf '\nType RESTORE to continue: '
  if ! read -r answer; then
    die "Restore cancelled."
  fi

  if [[ "${answer}" != "RESTORE" ]]; then
    die "Restore cancelled."
  fi

  section "Restoring project directories"
  for project_dir in "${project_dirs[@]}"; do
    if [[ -e "${temp_dir}/${project_dir}" ]]; then
      rm -rf "${PROJECT_ROOT:?}/${project_dir}"
      cp -a "${temp_dir}/${project_dir}" "${PROJECT_ROOT}/${project_dir}"
      ok "Restored ${project_dir}"
    fi
  done

  if [[ -e "${temp_dir}/opt/docker" ]]; then
    section "Restoring persistent data"
    sudo_cmd mkdir -p /opt
    sudo_cmd rm -rf "${data_root}"
    sudo_cmd cp -a "${temp_dir}/opt/docker" /opt/docker
    ok "Restored ${data_root}"
  fi

  ok "Restore completed."
}

main "$@"
