services:
  redis-exporter:
    image: oliver006/redis_exporter:v1.67.0
    container_name: redis-exporter
    restart: unless-stopped
    environment:
      REDIS_ADDR: redis://redis:6379
      REDIS_EXPORTER_LOG_FORMAT: txt
    networks:
      - monitoring
      - internal
    security_opt:
      - no-new-privileges:true

networks:
  monitoring:
    external: true
    name: monitoring
  internal:
    external: true
    name: internal
