services:
  traefik:
    image: traefik:v3.7.7
    container_name: traefik
    restart: unless-stopped

    security_opt:
      - no-new-privileges:true

    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - /opt/docker/platform/traefik/letsencrypt:/letsencrypt
      - /opt/docker/platform/traefik/logs:/var/log/traefik

    networks:
      - proxy
      - monitoring

    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.middlewares.traefik-https.redirectscheme.scheme=https
      - traefik.http.middlewares.traefik-https.redirectscheme.permanent=true
      - traefik.http.routers.traefik-http.rule=Host(`${SERVICE_HOST:-traefik.marca7.tech}`)
      - traefik.http.routers.traefik-http.entrypoints=web
      - traefik.http.routers.traefik-http.middlewares=traefik-https
      - traefik.http.routers.traefik.rule=Host(`${SERVICE_HOST:-traefik.marca7.tech}`)
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik.service=api@internal

networks:
  proxy:
    external: true
    name: proxy
  monitoring:
    external: true
    name: monitoring
